import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/colors';

export const homeStyles = StyleSheet.create({
  homeBanner: {
    position: 'relative',
  },
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  content: {
    flex: 1,
  },
  placeholder: {
    fontSize: 14,
    color: '#666666',
  },
  header: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: Colors.textInverse,
    flex: 1,
  },
  headerIcons: {
    flexDirection: 'row',
    gap: 12,
  },
  headerIconBtn: {
    width: 28,
    height: 28,
    borderRadius: 18,
    backgroundColor: Colors.backgroundPrimary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  
  headerActionBtn: {
    width: 28,
    height: 28,
    borderRadius: 18,
    backgroundColor: Colors.backgroundPrimary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  completionBanner: {
    backgroundColor: Colors.bannerBg,
    marginHorizontal: 16,
    padding: 10,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0,
    borderTopWidth: 4,
    borderTopColor: Colors.bannerTitle,
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
    marginTop: -25,
  },
  completionTextWrap: {
    flex: 1,
    paddingRight: 12,
  },
  completionLabel: {
    fontSize: 14,
    color: Colors.bannerTitle,
    fontFamily: 'NunitoSans-Bold',
  },
  completionSub: {
    color: Colors.bannerTitle,
    fontSize: 14,
    fontFamily: 'NunitoSans-Regular',
  },
  completionPct: {
    fontSize: 12,
    fontWeight: '500',
    color: Colors.bannerText,
    marginTop: 4,
    fontFamily: 'NunitoSans-Medium',
  },
  progressRing: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterResultsHeader: {
    backgroundColor: "#ffffff",
    marginHorizontal: 16,
    borderWidth: 0,
    borderRadius: 12,
    marginTop: -25,
    marginBottom: 20,
  },
  listHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  listHeaderTitle: {
    color: Colors.textPrimary,
  },
  filterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  filterIconWrapper: {
    position: 'relative',
  },
  filterDot: {
    position: 'absolute',
    top: -2,
    right: -4,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ef4444',
    borderWidth: 1,
    borderColor: '#ffffff',
  },
  filterBtnText: {
    fontSize: 14,
    color: Colors.primary,
    fontFamily: 'NunitoSans-Medium',
  },
  filtersChipRow: {
    paddingHorizontal: 16,
    paddingBottom: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.backgroundSecondary,
    borderRadius: 20,
    paddingVertical: 5,
    paddingHorizontal: 10,
    gap: 4,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  filterChipText: {
    fontSize: 12,
    color: Colors.textPrimary,
    fontWeight: '500',
    fontFamily: 'NunitoSans-Medium',
  },
  filterChipClose: {
    marginLeft: 2,
  },
  showingResultsLabel: {
    fontSize: 13,
    color: Colors.textSecondary,
    paddingHorizontal: 16,
    paddingBottom: 6,
    fontStyle: 'italic',
    fontFamily: 'NunitoSans-Regular',
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  emptyState: {
    alignItems: 'center',
    paddingTop: 60,
    paddingHorizontal: 32,
  },
  emptyText: {
    fontSize: 15,
    color: Colors.textSecondary,
    textAlign: 'center',
    marginTop: 12,
    fontFamily: 'NunitoSans-Regular',
  },
  loadingState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 60,
  },
  loadingText: {
    fontSize: 15,
    color: Colors.textSecondary,
    marginTop: 12,
    fontFamily: 'NunitoSans-Regular',
  },
  errorState: {
    alignItems: 'center',
    paddingTop: 60,
    paddingHorizontal: 32,
  },
  errorText: {
    fontSize: 15,
    color: '#ef4444',
    textAlign: 'center',
    fontFamily: 'NunitoSans-Regular',
  },
  retryBtn: {
    marginTop: 16,
    paddingVertical: 10,
    paddingHorizontal: 24,
    backgroundColor: Colors.primary,
    borderRadius: 8,
  },
  retryText: {
    fontSize: 14,
    color: Colors.textInverse,
    fontFamily: 'NunitoSans-Medium',
  },
});