import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/colors';

export const settingsStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#ffffff',
  },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#ffffff',
    position: 'relative',
  },
  backBtn: {
    position: 'absolute',
    left: 16,
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: Colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 16,
    fontFamily: 'NunitoSans-Bold',
    color: Colors.textPrimary,
  },
  headerRight: {
    position: 'absolute',
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  logoutText: {
    fontSize: 14,
    fontFamily: 'NunitoSans-Medium',
    color: Colors.danger,
  },

  sectionLabel: {
    fontSize: 12,
    fontFamily: 'NunitoSans-Regular',
    color: Colors.textTertiary,
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 6,
  },

  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 14,
    backgroundColor: '#ffffff',
  },
  menuIcon: {
    width: 22,
    alignItems: 'center',
  },
  menuLabel: {
    flex: 1,
    fontSize: 15,
    fontFamily: 'NunitoSans-Regular',
    color: Colors.textPrimary,
  },
  menuSeparator: {
    height: 1,
    backgroundColor: Colors.divider,
    marginLeft: 52,
  },

  sendMoneyBanner: {
    marginHorizontal: 16,
    marginTop: 24,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: Colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 18,
    gap: 12,
  },
  sendMoneyTextWrap: {
    flex: 1,
  },
  sendMoneyTitle: {
    fontSize: 16,
    fontFamily: 'NunitoSans-Bold',
    color: '#ffffff',
    marginBottom: 4,
  },
  sendMoneySubtitle: {
    fontSize: 12,
    fontFamily: 'NunitoSans-Regular',
    color: 'rgba(255,255,255,0.85)',
    lineHeight: 17,
  },
  sendMoneyIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  formSection: {
    paddingHorizontal: 16,
    paddingTop: 20,
  },
  subSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 14,
  },
  subSectionTitle: {
    fontSize: 13,
    fontFamily: 'NunitoSans-Regular',
    color: Colors.textTertiary,
  },
  fieldLabel: {
    fontSize: 14,
    fontFamily: 'NunitoSans-Bold',
    color: Colors.textPrimary,
    marginBottom: 8,
  },
  textInput: {
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: Colors.textPrimary,
    backgroundColor: '#ffffff',
    fontFamily: 'NunitoSans-Regular',
    flexDirection: 'row',
    alignItems: 'center',
  },
  textInputFocused: {
    borderColor: Colors.primary,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 8,
    paddingHorizontal: 14,
    marginBottom: 8,
    backgroundColor: '#ffffff',
  },
  inputRowFocused: {
    borderColor: Colors.primary,
  },
  inputRowText: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 15,
    color: Colors.textPrimary,
    fontFamily: 'NunitoSans-Regular',
  },
  passwordHint: {
    fontSize: 13,
    fontFamily: 'NunitoSans-Regular',
    color: Colors.textSecondary,
    lineHeight: 18,
    marginBottom: 24,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: Colors.divider,
    marginHorizontal: 16,
    marginVertical: 20,
  },
  deleteRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  deleteInfo: {
    flex: 1,
  },
  deleteTitle: {
    fontSize: 15,
    fontFamily: 'NunitoSans-Bold',
    color: Colors.textPrimary,
    marginBottom: 4,
  },
  deleteSubtitle: {
    fontSize: 13,
    fontFamily: 'NunitoSans-Regular',
    color: Colors.textSecondary,
  },
  deleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingTop: 2,
  },
  deleteBtnText: {
    fontSize: 14,
    fontFamily: 'NunitoSans-Medium',
    color: Colors.danger,
  },

  saveBtn: {
    marginHorizontal: 16,
    marginBottom: 24,
    backgroundColor: Colors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  saveBtnText: {
    fontSize: 16,
    fontFamily: 'NunitoSans-Bold',
    color: '#ffffff',
  },

  dialogOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  dialogBox: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 360,
  },
  dialogTitle: {
    fontSize: 16,
    fontFamily: 'NunitoSans-Bold',
    color: Colors.textPrimary,
    marginBottom: 10,
  },
  dialogBody: {
    fontSize: 14,
    fontFamily: 'NunitoSans-Regular',
    color: Colors.textSecondary,
    lineHeight: 20,
    marginBottom: 24,
  },
  dialogActions: {
    flexDirection: 'row',
    gap: 12,
  },
  dialogBtnCancel: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
  },
  dialogBtnCancelText: {
    fontSize: 14,
    fontFamily: 'NunitoSans-Medium',
    color: Colors.textPrimary,
  },
  dialogBtnDelete: {
    flex: 1,
    backgroundColor: Colors.danger,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
  },
  dialogBtnDeleteText: {
    fontSize: 14,
    fontFamily: 'NunitoSans-Bold',
    color: '#ffffff',
  },

  languageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 14,
  },
  languageLabel: {
    flex: 1,
    fontSize: 15,
    fontFamily: 'NunitoSans-Regular',
    color: Colors.textPrimary,
  },
  radioOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: Colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterActive: {
    borderColor: Colors.primary,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.primary,
  },

  sendMoneyScreen: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  redirectBody: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
  },
  redirectLogo: {
    width: 120,
    height: 60,
    marginBottom: 24,
  },
  redirectText: {
    fontSize: 14,
    fontFamily: 'NunitoSans-Regular',
    color: Colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 8,
  },
  redirectQuestion: {
    fontSize: 14,
    fontFamily: 'NunitoSans-Bold',
    color: Colors.textPrimary,
    textAlign: 'center',
  },
  proceedBtn: {
    marginHorizontal: 16,
    marginBottom: 24,
    backgroundColor: Colors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  proceedBtnText: {
    fontSize: 16,
    fontFamily: 'NunitoSans-Bold',
    color: '#ffffff',
  },
});
