export const staticStrings = {
    email: 'Email Address',
    emailInvalid: 'Please enter a valid email address.',
    getStarted: 'Get Started',
    alreadyRegistered: 'Already registered?',
    loginHere: 'Login here',
    login: 'Login',
    notYetRegistered: 'Not yet registered?',
    signUpHere: 'Sign up here',
    termsOfUse: 'Terms of Use',
    privacyPolicy: 'Privacy Policy',
    basicInformation: 'Basic Information',
    basicInfoText: 'To proceed, fill in the required information.',
    fullName: 'Full Name',
    next: 'Next',
    selectOption: 'Select option',
    gender: 'Gender',
    dateOfBirth: 'Date of Birth',
    nationality: 'Nationality',
    invalidEmailOrPass: 'Invalid email address or password.',
    emptyFullName: 'Please enter a name.',
    emptyGender: 'Please select a gender.',
    emptyNationality: 'Please select a nationality.',
    createPassword: 'Create Password',
    createPasswordInfoText: 'Let\'s finish setting you up. Please create a strong password.',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    submit: 'Submit',
    invalidPassword: 'Password must be at least 8 characters, alphanumeric, and contains uppercase and lowercase.',
    emptyConfirmPassword: 'Confirm password is empty.',
    incorrectConfirmPassword: 'Passwords do not match.',
    letsGo: 'Let\'s go!',
    thankYou: 'Thank you!',
    successCreateInfoText: 'You have successfully signed up! Now enjoy, and make the most out of this app!',
    cancelUserRegistration: 'Cancel User Registration',
    exitPrompt1: 'If you exit now, your info won\'t be saved. Discard changes and exit?',
    cancel: 'Cancel',
    exit: 'Exit',
    selectGender: 'Select Gender',
    female: 'Female',
    male: 'Male',
    selectCountry: 'Select Country',
    setDate: 'Set Date',
    selectDateOfBirth: 'Select Date of Birth',
    userRegistration: 'User Registration',
    userRegistrationPrompt1: 'Are you sure you want to register using the information above?',
    proceed: 'Proceed',
    creatingUserAccount: 'Creating user account...',
    emailShort: 'Email',
    signingIn: 'Signing in...',
}